# Document Processing System Configuration

# LLM Configuration
llm:
  provider: "mistral"  # Options: mistral, openai, huggingface
  model: "mistral-small-latest"  # mistral-small-latest, gpt-3.5-turbo, mistralai/Mistral-7B-Instruct-v0.3
  max_tokens: 2048
  temperature: 0.2
  output_format: "latex"

# Alternative LLM Configurations (uncomment to use)
# For Hugging Face:
# llm:
#   provider: "huggingface"
#   model: "mistralai/Mistral-7B-Instruct-v0.3"  # or "teknium/OpenHermes-2.5-Mistral-7B"
#   max_tokens: 2048
#   temperature: 0.2

# For OpenAI:
# llm:
#   provider: "openai"
#   model: "gpt-3.5-turbo"  # or "gpt-4"
#   max_tokens: 2048
#   temperature: 0.2

# Processing Configuration
processing:
  template: "academic"
  enable_enhancement: true
  chunk_strategy: "semantic"

# Output Configuration
output:
  directory: "outputs"
  format: "latex"
  extension: ".tex"
  generate_analysis: true

# Document Templates
templates:
  academic:
    sections:
      - name: "Abstract"
        prompt: "Rewrite as a concise abstract"
      - name: "Introduction"
        prompt: "Create compelling introduction"
      - name: "Methodology"
        prompt: "Describe methodology clearly"
      - name: "Results"
        prompt: "Present results with analysis"
      - name: "Conclusion"
        prompt: "Summarize contributions"
  
  bitcoin:
    sections:
      - name: "Abstract"
        prompt: "Bitcoin system abstract"
      - name: "Introduction"
        prompt: "Electronic payment problem"
      - name: "Transactions"
        prompt: "Digital signature chains"
      - name: "Proof-of-Work"
        prompt: "Consensus mechanism"
      - name: "Network"
        prompt: "Network protocol"
      - name: "Conclusion"
        prompt: "System benefits"

# Analysis Configuration
analysis:
  content_preservation_threshold: 0.9
  check_equations: true
  check_code_blocks: true
  check_lists: true