# Complete Configuration-Driven Document Processing System

# File handling configuration
supported_formats: ['.tex', '.txt', '.md', '.pdf']
file_encodings: ['utf-8', 'latin-1', 'ascii']
download_timeout: 30
arxiv_url_template: "https://arxiv.org/e-print/{arxiv_id}"

# LaTeX and content processing
latex_environments: 
  - 'equation'
  - 'align' 
  - 'gather'
  - 'multline'
  - 'enumerate'
  - 'itemize'
  - 'verbatim'
  - 'lstlisting'
  - 'figure'
  - 'table'
  - 'abstract'

# Regex patterns for content processing
patterns:
  section_extraction: '% --- (.+?) ---\n(.*?)(?=% --- |$)'
  environment_extraction: '(\\begin\{{({environments})\}}.*?\\end\{{\2\}})'
  equation_pattern: '\\begin\{equation\}.*?\\end\{equation\}'
  code_pattern: '\\begin\{verbatim\}.*?\\end\{verbatim\}'
  list_pattern: '\\begin\{enumerate\}.*?\\end\{enumerate\}'

# Content classification patterns
content_classifiers:
  equation: '\\begin\{equation\}'
  list: '\\begin\{(enumerate|itemize)\}'
  code: '\\begin\{(verbatim|lstlisting)\}'
  figure: '\\begin\{(figure|table)\}'
  paragraph: '.*'

default_content_type: 'paragraph'

# LLM Configuration
llm:
  provider: "mistral"
  model: "mistral-small-latest"
  max_tokens: 2048
  temperature: 0.2
  output_format: "latex"

# Generic API configurations for any LLM provider
api_configs:
  mistral:
    url: "https://api.mistral.ai/v1/chat/completions"
    api_key_env: "MISTRAL_API_KEY"
    default_model: "mistral-small-latest"
    default_max_tokens: 2048
    default_temperature: 0.2
    default_timeout: 30
    headers:
      Authorization: "Bearer {api_key}"
      Content-Type: "application/json"
    request_template:
      model: "{model}"
      messages: "{messages}"
      max_tokens: "{max_tokens}"
      temperature: "{temperature}"
    response_path: ['choices', 0, 'message', 'content']
  
  openai:
    url: "https://api.openai.com/v1/chat/completions"
    api_key_env: "OPENAI_API_KEY"
    default_model: "gpt-3.5-turbo"
    default_max_tokens: 2048
    default_temperature: 0.2
    default_timeout: 30
    headers:
      Authorization: "Bearer {api_key}"
      Content-Type: "application/json"
    request_template:
      model: "{model}"
      messages: "{messages}"
      max_tokens: "{max_tokens}"
      temperature: "{temperature}"
    response_path: ['choices', 0, 'message', 'content']
  
  huggingface:
    url: "https://api-inference.huggingface.co/models/{model}"
    api_key_env: "HUGGINGFACE_TOKEN"
    default_model: "mistralai/Mistral-7B-Instruct-v0.3"
    default_max_tokens: 2048
    default_temperature: 0.2
    default_timeout: 30
    headers:
      Authorization: "Bearer {api_key}"
    request_template:
      inputs: "{prompt}"
      parameters:
        max_new_tokens: "{max_tokens}"
        temperature: "{temperature}"
    response_path: [0, 'generated_text']
  
  anthropic:
    url: "https://api.anthropic.com/v1/messages"
    api_key_env: "ANTHROPIC_API_KEY"
    default_model: "claude-3-sonnet-20240229"
    default_max_tokens: 2048
    default_temperature: 0.2
    default_timeout: 30
    headers:
      x-api-key: "{api_key}"
      Content-Type: "application/json"
      anthropic-version: "2023-06-01"
    request_template:
      model: "{model}"
      max_tokens: "{max_tokens}"
      messages: "{messages}"
    response_path: ['content', 0, 'text']

# Configurable prompts with template variables
prompts:
  system_prompt: |
    You are a {output_format} expert. Output ONLY valid {output_format} content.
    STRICT RULES for {output_format}:
    - Use \section{{Title}} for sections, NOT ### Title
    - Use \textbf{{text}} for bold, NOT **text**
    - Use \begin{{itemize}} for lists, NOT - item
    - Preserve all equations exactly
    - NO Markdown syntax allowed
    - NO document structure (\documentclass, \begin{{document}})
  
  context_template: |
    CONTEXT: {context}
    
    TASK: {task}
    
    CONTENT:
    {content}
  
  default_section_prompt: "Process this content appropriately for the {section_name} section."
  
  abstract_prompt: "Rewrite as a concise abstract summarizing the main contributions."
  introduction_prompt: "Rewrite as a compelling introduction that motivates the work."
  methodology_prompt: "Describe the methodology clearly and systematically."
  results_prompt: "Present the results clearly with proper analysis."
  discussion_prompt: "Discuss the implications and significance of the results."
  conclusion_prompt: "Summarize the main contributions and future work."
  
  # Bitcoin-specific prompts
  bitcoin_summary_prompt: "Create a comprehensive summary covering key findings and results without equations or tables."
  bitcoin_transactions_prompt: "Explain how electronic coins work as chains of digital signatures."
  bitcoin_timestamp_prompt: "Describe the timestamp server solution."
  bitcoin_pow_prompt: "Explain the proof-of-work system and implementation."
  bitcoin_network_prompt: "Detail the network protocol and steps."
  bitcoin_incentive_prompt: "Explain the incentive mechanism for nodes."
  bitcoin_calculations_prompt: "Present the mathematical analysis of attack probabilities."

# Post-processing rules (pattern, replacement)
post_processing_rules:
  - ['^#{3}\s*(.+)$', '\\section{\1}']
  - ['^#{4}\s*(.+)$', '\\subsection{\1}']
  - ['\*\*([^*]+)\*\*', '\\textbf{\1}']
  - ['\*([^*]+)\*', '\\textit{\1}']
  - ['^-\s+(.+)$', '\\item \1']

# Document templates
document_templates:
  academic:
    header:
      - "\\documentclass{article}"
      - "\\usepackage[utf8]{inputenc}"
      - "\\usepackage{amsmath}"
      - "\\usepackage{graphicx}"
      - ""
      - "\\title{Processed Document}"
      - "\\author{Document Processing System}"
      - "\\date{\\today}"
      - ""
      - "\\begin{document}"
      - "\\maketitle"
      - ""
    section_order: ["Abstract", "Introduction", "Methodology", "Results", "Discussion", "Conclusion"]
    footer:
      - "\\end{document}"
  
  bitcoin:
    header:
      - "\\documentclass{article}"
      - "\\usepackage[utf8]{inputenc}"
      - "\\usepackage{amsmath}"
      - "\\usepackage{graphicx}"
      - ""
      - "\\title{Bitcoin: A Peer-to-Peer Electronic Cash System}"
      - "\\author{Enhanced Version}"
      - "\\date{\\today}"
      - ""
      - "\\begin{document}"
      - "\\maketitle"
      - ""
    section_order: 
      - "Summary"
      - "Abstract" 
      - "Introduction"
      - "Transactions"
      - "Timestamp Server"
      - "Proof-of-Work"
      - "Network"
      - "Incentive"
      - "Reclaiming Disk Space"
      - "Simplified Payment Verification"
      - "Combining and Splitting Value"
      - "Privacy"
      - "Major and Minor Assumptions"
      - "Calculations"
      - "Conclusion"
    footer:
      - "\\end{document}"

# Template section configurations
templates:
  academic:
    sections:
      - name: "Abstract"
        prompt_name: "abstract_prompt"
      - name: "Introduction"
        prompt_name: "introduction_prompt"
      - name: "Methodology"
        prompt_name: "methodology_prompt"
      - name: "Results"
        prompt_name: "results_prompt"
      - name: "Discussion"
        prompt_name: "discussion_prompt"
      - name: "Conclusion"
        prompt_name: "conclusion_prompt"
  
  bitcoin:
    sections:
      - name: "Summary"
        prompt_name: "bitcoin_summary_prompt"
      - name: "Abstract"
        prompt_name: "abstract_prompt"
      - name: "Introduction"
        prompt_name: "introduction_prompt"
      - name: "Transactions"
        prompt_name: "bitcoin_transactions_prompt"
      - name: "Timestamp Server"
        prompt_name: "bitcoin_timestamp_prompt"
      - name: "Proof-of-Work"
        prompt_name: "bitcoin_pow_prompt"
      - name: "Network"
        prompt_name: "bitcoin_network_prompt"
      - name: "Incentive"
        prompt_name: "bitcoin_incentive_prompt"
      - name: "Calculations"
        prompt_name: "bitcoin_calculations_prompt"
      - name: "Conclusion"
        prompt_name: "conclusion_prompt"

# Processing configuration
processing:
  template: "academic"
  enable_enhancement: true
  chunk_strategy: "semantic"
  quality_threshold: 0.8

# Output configuration
output:
  directory: "outputs"
  format: "latex"
  extension: ".tex"
  generate_analysis: true

# Analysis patterns for content preservation checking
analysis_patterns:
  equations: '\\begin\{equation\}.*?\\end\{equation\}'
  code_blocks: '\\begin\{verbatim\}.*?\\end\{verbatim\}'
  lists: '\\begin\{enumerate\}.*?\\end\{enumerate\}'
  figures: '\\begin\{figure\}.*?\\end\{figure\}'

# Content cleaning patterns for analysis
cleaning_patterns:
  - '\\documentclass.*?\\begin\{document\}'
  - '\\end\{document\}'
  - '\\title\{.*?\}'
  - '\\author\{.*?\}'
  - '\\date\{.*?\}'
  - '\\maketitle'
  - '% --- .+? ---'
  - '% .+'

# Context and memory management
max_context_length: 200
preview_length: 100

# Logging configuration
logging:
  level: "INFO"
  verbose_output: true
  save_logs: true

# Document combination strategies
combination_strategies:
  merge:
    method: "merge"
    merge_template: |
      % From Document 1
      {doc1_content}
      
      % From Document 2
      {doc2_content}
  
  interleave:
    method: "interleave"
    interleave_template: "% Document {doc_num} - Chunk {chunk_num}\n{content}"
  
  append:
    method: "append"
    part_template: "Part {part_num} - {section}"
  
  smart_merge:
    method: "smart_merge"
    section_priority:
      - "Abstract"
      - "Introduction"
      - "Background"
      - "Methodology"
      - "Methods"
      - "Results"
      - "Discussion"
      - "Conclusion"
      - "References"
  
  bitcoin_merge:
    method: "smart_merge"
    section_priority:
      - "Summary"
      - "Abstract"
      - "Introduction"
      - "Transactions"
      - "Timestamp Server"
      - "Proof-of-Work"
      - "Network"
      - "Incentive"
      - "Calculations"
      - "Conclusion"

# Performance and limits
performance:
  parallel_processing: false
  cache_responses: false
  max_chunk_size: 2000
  min_chunk_size: 100