# Document Processing System Configuration

# LLM Configuration
llm:
  provider: "mistral"  # Options: mistral, openai, huggingface
  model: "mistral-small-latest"  # Model name
  max_tokens: 2048  # Maximum response length
  temperature: 0.2  # Creativity level (0.0-1.0)
  timeout: 30  # Request timeout in seconds
  output_format: "latex"  # Output format: latex, markdown

# Processing Configuration
processing:
  template: "academic"  # Document template: academic, bitcoin, technical
  enable_enhancement: true  # Enable LLM enhancement
  chunk_strategy: "semantic"  # Chunking strategy: semantic, regex
  multi_pass: false  # Enable multi-pass processing
  quality_threshold: 0.8  # Quality threshold for acceptance

# Document Templates
templates:
  academic:
    sections:
      - name: "Abstract"
        prompt: "Rewrite as a concise abstract summarizing the main contributions."
      - name: "Introduction" 
        prompt: "Rewrite as a compelling introduction that motivates the work."
      - name: "Methodology"
        prompt: "Describe the methodology clearly and systematically."
      - name: "Results"
        prompt: "Present the results clearly with proper analysis."
      - name: "Discussion"
        prompt: "Discuss the implications and significance of the results."
      - name: "Conclusion"
        prompt: "Summarize the main contributions and future work."
  
  bitcoin:
    sections:
      - name: "Summary"
        prompt: "Create a comprehensive summary covering key findings and results."
      - name: "Abstract"
        prompt: "Rewrite as a concise abstract for the peer-to-peer electronic cash system."
      - name: "Introduction"
        prompt: "Explain the problem with current payment systems."
      - name: "Transactions"
        prompt: "Explain how electronic coins work as chains of digital signatures."
      - name: "Timestamp Server"
        prompt: "Describe the timestamp server solution."
      - name: "Proof-of-Work"
        prompt: "Explain the proof-of-work system and implementation."
      - name: "Network"
        prompt: "Detail the network protocol and steps."
      - name: "Incentive"
        prompt: "Explain the incentive mechanism for nodes."
      - name: "Calculations"
        prompt: "Present the mathematical analysis of attack probabilities."
      - name: "Conclusion"
        prompt: "Summarize the proposed system and its benefits."

# Output Configuration
output:
  directory: "outputs"  # Output directory
  format: "latex"  # Primary output format
  generate_analysis: true  # Generate analysis reports
  save_individual_sections: true  # Save individual section files
  create_pdf: false  # Automatically compile to PDF
  
# Analysis Configuration
analysis:
  content_preservation_threshold: 0.9  # Minimum content preservation ratio
  check_equations: true  # Verify equation preservation
  check_code_blocks: true  # Verify code block preservation
  check_lists: true  # Verify list preservation
  generate_diff: true  # Generate content diff
  
# Format Enforcement
format:
  strict_latex: true  # Enforce strict LaTeX syntax
  auto_fix_markdown: true  # Automatically fix Markdown syntax
  validate_output: true  # Validate output format
  
# Logging Configuration
logging:
  level: "INFO"  # Log level: DEBUG, INFO, WARNING, ERROR
  save_logs: true  # Save logs to file
  verbose_output: true  # Verbose console output

# Performance Configuration
performance:
  parallel_processing: false  # Enable parallel section processing
  cache_llm_responses: false  # Cache LLM responses
  max_chunk_size: 2000  # Maximum chunk size in characters
  min_chunk_size: 100  # Minimum chunk size in characters

# Security Configuration
security:
  validate_inputs: true  # Validate input files
  sanitize_outputs: true  # Sanitize output content
  rate_limiting: true  # Enable API rate limiting