import pytest

from langgraph_workflow import DocumentProcessingWorkflow
from langgraph_state import ErrorSeverity


@pytest.mark.asyncio
async def test_new_langgraph_integration_success(tmp_path):
    # Create a simple text document with enough content to pass quality gates
    doc_path = tmp_path / "sample_document.txt"
    content = (
        "This is a simple document used to validate the new LangGraph integration. "
        * 10
    )  # ensures length > 500
    doc_path.write_text(content, encoding="utf-8")

    orchestrator = DocumentProcessingWorkflow(
        config={
            "output_format": "json",
            # Leave defaults for optional stages; fallback implementations will handle them
            "enable_knowledge_graph": True,
            "enable_semantic_mapping": True,
        }
    )

    state = await orchestrator.process_document(str(doc_path))

    # Basic assertions for successful end-to-end processing
    # No critical errors should be present
    assert not any(e.severity == ErrorSeverity.CRITICAL for e in state.errors), (
        f"Critical errors encountered: {[e.message for e in state.errors]}"
    )

    # At least one output should be generated
    assert hasattr(state, "outputs") and len(state.outputs) >= 1, "No outputs generated by workflow"

    # Analytics should be populated (processing times, metrics, etc.)
    assert state.analytics is not None, "Analytics not populated"
    assert getattr(state.analytics, "processing_start_time", None) is not None, "Processing start time missing"


@pytest.mark.asyncio
async def test_new_langgraph_integration_missing_file():
    orchestrator = DocumentProcessingWorkflow(config={"output_format": "json"})

    state = await orchestrator.process_document("__non_existent_file__.txt")

    # Expect at least one error flagged as critical from initialization
    assert any(e.severity == ErrorSeverity.CRITICAL for e in state.errors), (
        "Expected a critical error when processing a non-existent file"
    )